version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/httc
      - SPRING_DATASOURCE_USERNAME=hackerphobia
      - SPRING_DATASOURCE_PASSWORD=hackerphobia
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=httc
      - MYSQL_USER=hackerphobia
      - MYSQL_PASSWORD=hackerphobia
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: 