version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/httc
      - SPRING_DATASOURCE_USERNAME=hackerphobia
      - SPRING_DATASOURCE_PASSWORD=hackerphobia
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=httc
      - MYSQL_USER=hackerphobia
      - MYSQL_PASSWORD=hackerphobia
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: always

  sql-init:
    image: mysql:8.0
    container_name: sql_init
    depends_on:
      - app
    entrypoint: >
      bash -c "
        sleep 30 &&
        mysql -h mysql -u root -proot_password httc < /sql/init-data.sql &&
        mysql -h mysql -u root -proot_password httc < /sql/init-db.sql
      "
    volumes:
      - ./init-db.sql:/sql/init-db.sql
      - ./init-data.sql:/sql/init-data.sql
    restart: "no"

volumes:
  mysql_data: 