@startuml notification
left to right direction
skinparam packageStyle rectangle

actor "Quản trị viên" as Admin

rectangle "Phân quyền sử dụng chức năng" {
    usecase "Xem danh sách chức năng của nhóm" as UC1
    usecase "Xóa chức năng khỏi nhóm" as UC2
    usecase "Thêm chức năng cho nhóm" as UC3

    note right of UC3
        Chú ý cho người dùng
        chọn loại chức năng,
        hỗ trợ chọn tất cả
        hoặc 1 số chức năng
        trong loại đó
    end note

    Admin --> UC1
    Admin --> UC2
    Admin --> UC3
}
@enduml 